import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "ru" | "tj" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ru: {
    navAbout: "О компании",
    navCategories: "Категории",
    navMasters: "Мастера",
    navHowItWorks: "Как это работает",
    navContacts: "Контакты",
    navBecomeMaster: "Стать мастером",
    login: "Вход",
    logout: "Выйти",
    cabinet: "Кабинет",
    admin: "Админ",
    masterCabinet: "Кабинет мастера",
    clientCabinet: "Личный кабинет",
    subscription: "Подписка",
    heroTitle: "Мастер приедет уже сегодня",
    heroSubtitle: "Проверенные мастера • Выезд от 30 минут • Гарантия работ",
    heroDescription: "Мы быстро подбираем мастера рядом с вами — для срочного ремонта и бытовых задач по дому.",
    heroOrderButton: "Заказать мастера",
    heroEmergencyButton: "🚨 Аварийный мастер 24/7",
    heroEmergencySubtext: "выезд 30–60 минут",
    trustTime: "За 1 час",
    trustTimeDesc: "мастер приедет",
    trustRating: "4.9",
    trustRatingDesc: "средний рейтинг",
    trustOrders: "5000+",
    trustOrdersDesc: "выполненных заказов",
    aboutTitle: "Мастер Час — сервис быстрых и надежных мастеров",
    aboutDescription: "Мастер Час — это онлайн-сервис, который помогает быстро найти проверенного мастера рядом с вами.",
    aboutFeature1Title: "Проверенные мастера",
    aboutFeature1Desc: "Все мастера проходят проверку документов и навыков перед началом работы",
    aboutFeature2Title: "Прозрачные цены",
    aboutFeature2Desc: "Вы знаете стоимость до начала работ, без скрытых платежей",
    aboutFeature3Title: "Быстрый выезд",
    aboutFeature3Desc: "Мастер приедет в течение часа или в удобное для вас время",
    aboutFeature4Title: "Поддержка 24/7",
    aboutFeature4Desc: "Мы всегда на связи и поможем решить любой вопрос",
    howItWorksTitle: "Как заказать мастера за 3 простых шага",
    howItWorksStep1Title: "Выберите услугу",
    howItWorksStep1Desc: "Укажите, что у вас сломалось или что нужно сделать.",
    howItWorksStep2Title: "Опишите проблему",
    howItWorksStep2Desc: "Добавьте детали, чтобы мастер подготовился заранее.",
    howItWorksStep3Title: "Мастер выезжает",
    howItWorksStep3Desc: "Специалист приедет в удобное для вас время.",
    howItWorksFooter: "Без звонков, без ожиданий, всё онлайн.",
    categoriesTitle: "Каталог услуг",
    categoriesDescription: "Выберите категорию и закажите мастера в несколько кликов.",
    categoryElectric: "Электрика",
    categoryPlumbing: "Сантехника",
    categoryCleaning: "Клининг",
    categoryFurniture: "Сборка мебели",
    categoryRenovation: "Отделка",
    categorySecurity: "Видеонаблюдение",
    categoryWelding: "Сварка",
    categoryRepair: "Ремонт техники",
    categorySmartHome: "Умный дом",
    categoryGarage: "Подвалы и гаражи",
    categoryTurnkey: "Ремонт под ключ",
    categoryOther: "Другие услуги",
    categoryEmergency: "Аварийные услуги 24/7",
    categoryEmergencyBadge: "Срочно",
    categoryPriceFrom: "от",
    categoryOrderButton: "Заказать мастера",
    contactsTitle: "Свяжитесь с нами",
    contactsDescription: "Если у вас есть вопросы, предложения или срочная ситуация — мы всегда на связи.",
    contactsPhone: "Телефон",
    contactsEmail: "Email",
    contactsWorkHours: "Работаем",
    contactsWorkHoursValue: "24/7",
    becomeMasterTitle: "Станьте мастером MasterChas",
    becomeMasterSubtitle: "Присоединяйтесь к команде профессионалов и получайте заказы каждый день",
    becomeMasterBenefit1: "Стабильный поток заказов",
    becomeMasterBenefit2: "Гибкий график работы",
    becomeMasterBenefit3: "Честные выплаты",
    becomeMasterBenefit4: "Поддержка 24/7",
    becomeMasterFormTitle: "Оставить заявку",
    becomeMasterFormName: "Ваше имя",
    becomeMasterFormPhone: "Телефон",
    becomeMasterFormSpecialty: "Специализация",
    becomeMasterFormExperience: "Опыт работы (лет)",
    becomeMasterFormSubmit: "Отправить заявку",
    becomeMasterFormSuccess: "Спасибо! Мы свяжемся с вами в ближайшее время.",
    servicesTitle: "Наши услуги",
    servicesSubtitle: "Широкий спектр услуг для дома и бизнеса",
    serviceElectric: "Электрика",
    servicePlumbing: "Сантехника",
    serviceCleaning: "Клининг",
    serviceFurniture: "Сборка мебели",
    serviceRenovation: "Отделка",
    serviceSecurity: "Видеонаблюдение",
    serviceWelding: "Сварка",
    serviceBasement: "Подвалы и гаражи",
    serviceTurnkey: "Ремонт под ключ",
    serviceRepair: "Ремонт техники",
    serviceSmartHome: "Умный дом",
    serviceOther: "Другие услуги",
    formName: "Ваше имя",
    formPhone: "Телефон",
    formService: "Выберите услугу",
    formDistrict: "Район",
    formComment: "Комментарий (необязательно)",
    formSubmit: "Отправить заявку",
    formSuccess: "Спасибо! Мы скоро свяжемся с вами",
    districtSino: "Сино",
    districtFirdausi: "Фирдавси",
    districtShomansur: "Шохмансур",
    districtIsmoili: "Исмоили Сомони",
    footerAboutText: "Мастер Час — надёжный сервис вызова мастеров в Душанбе",
    footerContacts: "Контакты",
    footerDistricts: "Районы работы",
    footerRights: "© 2025 Мастер Час. Все права защищены",
    footerServices: "Услуги",
    footerSubscriptions: "Подписки",
    footerBecomeMaster: "Стать мастером",
    footerForBusiness: "Для бизнеса",
    footerPrivacy: "Политика конфиденциальности",
    footerTerms: "Условия использования",
    viewAllCategories: "Смотреть все категории",
    learnMore: "Подробнее",
    qualityGuarantee: "Гарантия качества",
    qualityGuaranteeDesc: "Если что-то пойдёт не так — мы вернём деньги",
    step: "Шаг",
    orderModalTitle: "Оформить заказ",
    orderModalDesc: "Заполните форму и мы подберём мастера",
    orderModalSubmit: "Отправить",
    orderModalSuccess: "Заявка отправлена! Мы скоро свяжемся.",
  },
  tj: {
    navAbout: "Дар бораи мо",
    navCategories: "Категорияҳо",
    navHowItWorks: "Чӣ тавр кор мекунад",
    navContacts: "Тамосҳо",
    navBecomeMaster: "Усто шудан",
    login: "Вуруд",
    logout: "Баромадан",
    cabinet: "Кабинет",
    admin: "Админ",
    masterCabinet: "Кабинети усто",
    clientCabinet: "Кабинети шахсӣ",
    subscription: "Обуна",
    heroTitle: "Усто имрӯз меояд",
    heroSubtitle: "Устоони тасдиқшуда • Баромадан аз 30 дақиқа • Кафолати кор",
    heroDescription: "Мо зуд усторо дар наздикии шумо интихоб мекунем — барои таъмири зудӣ ва корҳои рӯзмарра.",
    heroOrderButton: "Усто фармудан",
    heroEmergencyButton: "🚨 Устои таъҷилӣ 24/7",
    heroEmergencySubtext: "баромадан 30–60 дақиқа",
    trustTime: "Дар 1 соат",
    trustTimeDesc: "усто меояд",
    trustRating: "4.9",
    trustRatingDesc: "рейтинги миёна",
    trustOrders: "5000+",
    trustOrdersDesc: "фармоишҳои иҷрошуда",
    aboutTitle: "Мастер Час — хидмати устоони зуд ва боэътимод",
    aboutDescription: "Мастер Час — ин хидмати онлайн аст, ки ба шумо кӯмак мекунад устои тасдиқшударо дар наздикиатон зуд пайдо кунед.",
    aboutFeature1Title: "Устоони тасдиқшуда",
    aboutFeature1Desc: "Ҳамаи устоон пеш аз оғози кор тафтиши ҳуҷҷатҳо ва малакаро мегузаранд",
    aboutFeature2Title: "Нархҳои шаффоф",
    aboutFeature2Desc: "Шумо нархро пеш аз оғози кор медонед, бе пардохтҳои пинҳонӣ",
    aboutFeature3Title: "Баромадани зуд",
    aboutFeature3Desc: "Усто дар давоми як соат ё дар вақти муносиби шумо меояд",
    aboutFeature4Title: "Дастгирии 24/7",
    aboutFeature4Desc: "Мо ҳамеша дар тамос ҳастем ва ба ҳар гуна савол кӯмак мекунем",
    howItWorksTitle: "Чӣ тавр усторо дар 3 қадам фармоиш додан",
    howItWorksStep1Title: "Хидматро интихоб кунед",
    howItWorksStep1Desc: "Нишон диҳед, ки чӣ чиз вайрон шуд ё чӣ кор бояд кард.",
    howItWorksStep2Title: "Мушкилиро тавсиф кунед",
    howItWorksStep2Desc: "Тафсилот илова кунед, то усто пешакӣ омода шавад.",
    howItWorksStep3Title: "Усто меравад",
    howItWorksStep3Desc: "Мутахассис дар вақти муносиби шумо меояд.",
    howItWorksFooter: "Бе зангҳо, бе интизорӣ, ҳама чиз онлайн.",
    categoriesTitle: "Каталоги хидматҳо",
    categoriesDescription: "Категорияро интихоб кунед ва усторо дар якчанд клик фармоиш диҳед.",
    categoryElectric: "Барқ",
    categoryPlumbing: "Сантехника",
    categoryCleaning: "Тозакунӣ",
    categoryFurniture: "Ҷамъкунии мебел",
    categoryRenovation: "Ороиш",
    categorySecurity: "Видеоназорат",
    categoryWelding: "Ҷӯшкорӣ",
    categoryRepair: "Таъмири техника",
    categorySmartHome: "Хонаи зиракона",
    categoryGarage: "Зеризамин ва гаражҳо",
    categoryTurnkey: "Таъмири пурра",
    categoryOther: "Хидматҳои дигар",
    categoryEmergency: "Хидматҳои таъҷилӣ 24/7",
    categoryEmergencyBadge: "Зудӣ",
    categoryPriceFrom: "аз",
    categoryOrderButton: "Усто фармудан",
    contactsTitle: "Бо мо тамос гиред",
    contactsDescription: "Агар саволҳо, пешниҳодҳо ё ҳолати зудӣ дошта бошед — мо ҳамеша дар тамос ҳастем.",
    contactsPhone: "Телефон",
    contactsEmail: "Email",
    contactsWorkHours: "Кор мекунем",
    contactsWorkHoursValue: "24/7",
    becomeMasterTitle: "Устои MasterChas шавед",
    becomeMasterSubtitle: "Ба дастаи мутахассисон ҳамроҳ шавед ва ҳар рӯз фармоиш гиред",
    becomeMasterBenefit1: "Ҷараёни устувори фармоишҳо",
    becomeMasterBenefit2: "Ҷадвали кори чандир",
    becomeMasterBenefit3: "Пардохтҳои одилона",
    becomeMasterBenefit4: "Дастгирии 24/7",
    becomeMasterFormTitle: "Дархост додан",
    becomeMasterFormName: "Номи шумо",
    becomeMasterFormPhone: "Телефон",
    becomeMasterFormSpecialty: "Ихтисос",
    becomeMasterFormExperience: "Таҷрибаи кор (сол)",
    becomeMasterFormSubmit: "Фиристодани дархост",
    becomeMasterFormSuccess: "Ташаккур! Мо зуд бо шумо тамос мегирем.",
    servicesTitle: "Хидматҳои мо",
    servicesSubtitle: "Хидматҳои васеъ барои хона ва бизнес",
    serviceElectric: "Барқкорӣ",
    servicePlumbing: "Сантехника",
    serviceCleaning: "Тозакунӣ",
    serviceFurniture: "Ҷамъкунии мебел",
    serviceRenovation: "Таъмири хона",
    serviceSecurity: "Видеоназорат",
    serviceWelding: "Ҷӯшкорӣ",
    serviceBasement: "Зеҳзамин ва гаражҳо",
    serviceTurnkey: "Таъмир зери калид",
    serviceRepair: "Таъмири техника",
    serviceSmartHome: "Хонаи зирак",
    serviceOther: "Дигар хидматҳо",
    formName: "Номи шумо",
    formPhone: "Телефон",
    formService: "Хидматро интихоб кунед",
    formDistrict: "Ноҳия",
    formComment: "Шарҳ (ихтиёрӣ)",
    formSubmit: "Фиристодани фармоиш",
    formSuccess: "Ташаккур! Мо зуд бо шумо тамос мегирем",
    districtSino: "Сино",
    districtFirdausi: "Фирдавсӣ",
    districtShomansur: "Шоҳмансур",
    districtIsmoili: "Исмоилӣ Сомонӣ",
    footerAboutText: "Мастер Час — хидмати боэътимоди даъвати устоон дар Душанбе",
    footerContacts: "Тамосҳо",
    footerDistricts: "Ноҳияҳои кор",
    footerRights: "© 2025 Мастер Час. Ҳамаи ҳуқуқҳо ҳифз шудаанд",
    footerServices: "Хидматҳо",
    footerSubscriptions: "Обунаҳо",
    footerBecomeMaster: "Усто шудан",
    footerForBusiness: "Барои бизнес",
    footerPrivacy: "Сиёсати махфият",
    footerTerms: "Шартҳои истифода",
    viewAllCategories: "Ҳамаи категорияҳоро дидан",
    learnMore: "Бештар",
    qualityGuarantee: "Кафолати сифат",
    qualityGuaranteeDesc: "Агар чизе хато шавад — мо пулро бармегардонем",
    step: "Қадам",
    orderModalTitle: "Фармоиш додан",
    orderModalDesc: "Формаро пур кунед ва мо усторо интихоб мекунем",
    orderModalSubmit: "Фиристодан",
    orderModalSuccess: "Дархост фиристода шуд! Мо зуд тамос мегирем.",
  },
  en: {
    navAbout: "About Us",
    navCategories: "Categories",
    navHowItWorks: "How It Works",
    navContacts: "Contacts",
    navBecomeMaster: "Become a Master",
    login: "Login",
    logout: "Logout",
    cabinet: "Cabinet",
    admin: "Admin",
    masterCabinet: "Master Cabinet",
    clientCabinet: "My Account",
    subscription: "Subscription",
    heroTitle: "Master will arrive today",
    heroSubtitle: "Verified masters • Arrival from 30 minutes • Work guarantee",
    heroDescription: "We quickly find a master near you — for urgent repairs and household tasks.",
    heroOrderButton: "Order a Master",
    heroEmergencyButton: "🚨 Emergency Master 24/7",
    heroEmergencySubtext: "arrival 30–60 minutes",
    trustTime: "Within 1 hour",
    trustTimeDesc: "master arrives",
    trustRating: "4.9",
    trustRatingDesc: "average rating",
    trustOrders: "5000+",
    trustOrdersDesc: "completed orders",
    aboutTitle: "Master Chas — Fast and Reliable Masters Service",
    aboutDescription: "Master Chas is an online service that helps you quickly find a verified master near you.",
    aboutFeature1Title: "Verified Masters",
    aboutFeature1Desc: "All masters undergo document and skill verification before starting work",
    aboutFeature2Title: "Transparent Prices",
    aboutFeature2Desc: "You know the cost before work begins, no hidden fees",
    aboutFeature3Title: "Quick Arrival",
    aboutFeature3Desc: "Master arrives within an hour or at your convenient time",
    aboutFeature4Title: "24/7 Support",
    aboutFeature4Desc: "We're always in touch and will help solve any issue",
    howItWorksTitle: "How to order a master in 3 simple steps",
    howItWorksStep1Title: "Choose a service",
    howItWorksStep1Desc: "Indicate what's broken or what needs to be done.",
    howItWorksStep2Title: "Describe the problem",
    howItWorksStep2Desc: "Add details so the master can prepare in advance.",
    howItWorksStep3Title: "Master is on the way",
    howItWorksStep3Desc: "A specialist will arrive at your convenient time.",
    howItWorksFooter: "No calls, no waiting, everything is online.",
    categoriesTitle: "Service Catalog",
    categoriesDescription: "Choose a category and order a master in a few clicks.",
    categoryElectric: "Electrical",
    categoryPlumbing: "Plumbing",
    categoryCleaning: "Cleaning",
    categoryFurniture: "Furniture Assembly",
    categoryRenovation: "Renovation",
    categorySecurity: "Video Surveillance",
    categoryWelding: "Welding",
    categoryRepair: "Appliance Repair",
    categorySmartHome: "Smart Home",
    categoryGarage: "Basements & Garages",
    categoryTurnkey: "Turnkey Renovation",
    categoryOther: "Other Services",
    categoryEmergency: "Emergency Services 24/7",
    categoryEmergencyBadge: "Urgent",
    categoryPriceFrom: "from",
    categoryOrderButton: "Order a Master",
    contactsTitle: "Contact Us",
    contactsDescription: "If you have questions, suggestions, or an urgent situation — we're always in touch.",
    contactsPhone: "Phone",
    contactsEmail: "Email",
    contactsWorkHours: "Working hours",
    contactsWorkHoursValue: "24/7",
    becomeMasterTitle: "Become a MasterChas Master",
    becomeMasterSubtitle: "Join the team of professionals and get orders every day",
    becomeMasterBenefit1: "Steady flow of orders",
    becomeMasterBenefit2: "Flexible work schedule",
    becomeMasterBenefit3: "Fair payments",
    becomeMasterBenefit4: "24/7 Support",
    becomeMasterFormTitle: "Submit Application",
    becomeMasterFormName: "Your name",
    becomeMasterFormPhone: "Phone",
    becomeMasterFormSpecialty: "Specialty",
    becomeMasterFormExperience: "Work experience (years)",
    becomeMasterFormSubmit: "Submit Application",
    becomeMasterFormSuccess: "Thank you! We will contact you soon.",
    servicesTitle: "Our Services",
    servicesSubtitle: "Wide range of services for home and business",
    serviceElectric: "Electrical",
    servicePlumbing: "Plumbing",
    serviceCleaning: "Cleaning",
    serviceFurniture: "Furniture Assembly",
    serviceRenovation: "Renovation",
    serviceSecurity: "Video Surveillance",
    serviceWelding: "Welding",
    serviceBasement: "Basements & Garages",
    serviceTurnkey: "Turnkey Renovation",
    serviceRepair: "Appliance Repair",
    serviceSmartHome: "Smart Home",
    serviceOther: "Other Services",
    formName: "Your Name",
    formPhone: "Phone",
    formService: "Select Service",
    formDistrict: "District",
    formComment: "Comment (optional)",
    formSubmit: "Submit Request",
    formSuccess: "Thank you! We'll contact you soon",
    districtSino: "Sino",
    districtFirdausi: "Firdausi",
    districtShomansur: "Shomansur",
    districtIsmoili: "Ismoili Somoni",
    footerAboutText: "Master Chas — reliable master call service in Dushanbe",
    footerContacts: "Contacts",
    footerDistricts: "Service Areas",
    footerRights: "© 2025 Master Chas. All rights reserved",
    footerServices: "Services",
    footerSubscriptions: "Subscriptions",
    footerBecomeMaster: "Become a Master",
    footerForBusiness: "For Business",
    footerPrivacy: "Privacy Policy",
    footerTerms: "Terms of Service",
    viewAllCategories: "View all categories",
    learnMore: "Learn more",
    qualityGuarantee: "Quality Guarantee",
    qualityGuaranteeDesc: "If something goes wrong — we'll refund",
    step: "Step",
    orderModalTitle: "Place an Order",
    orderModalDesc: "Fill out the form and we'll find a master",
    orderModalSubmit: "Submit",
    orderModalSuccess: "Request sent! We'll contact you soon.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("ru");

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)["ru"]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
