import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "ru" | "tj" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Nav
    navAbout: "О нас",
    navCategories: "Услуги",
    navMasters: "Мастера",
    navHowItWorks: "Как это работает",
    navContacts: "Контакты",
    navBecomeMaster: "Стать мастером",
    navShop: "Магазин",
    login: "Войти",
    logout: "Выйти",
    cabinet: "Кабинет",
    admin: "Админ",
    masterCabinet: "Кабинет мастера",
    clientCabinet: "Мой кабинет",
    subscription: "Подписка",

    // Hero homepage
    heroTitle: "Усто ба хонаатон меояд",
    heroSubtitle: "Устоони тасдиқшуда • Баромадан аз 30 дақиқа • Кафолати кор",
    heroDescription: "Мастер Час — сервис вызова мастеров на дом в Душанбе. Электрика, сантехника, уборка, ремонт техники и другие услуги — быстро, надёжно, по честным ценам в сомони.",
    heroOrderButton: "Вызвать мастера",
    heroEmergencyButton: "🚨 Аварийный мастер 24/7",
    heroEmergencySubtext: "выезд 30–60 минут по Душанбе",

    // Trust bar
    trustTime: "За 1 час",
    trustTimeDesc: "мастер будет у вас",
    trustRating: "4.9",
    trustRatingDesc: "средний рейтинг мастеров",
    trustOrders: "5000+",
    trustOrdersDesc: "выполнено заказов в Душанбе",

    // About
    aboutTitle: "Мастер Час — сервис мастеров на дом в Душанбе",
    aboutDescription: "Мы помогаем жителям Душанбе быстро найти проверенного мастера для любых бытовых задач — от установки розетки до ремонта под ключ.",
    aboutFeature1Title: "Проверенные мастера",
    aboutFeature1Desc: "Каждый мастер проходит проверку документов и навыков. Работаем только с надёжными специалистами Душанбе.",
    aboutFeature2Title: "Цены в сомони",
    aboutFeature2Desc: "Прозрачные цены без скрытых доплат. Вы знаете стоимость до начала работ.",
    aboutFeature3Title: "Выезд по всему Душанбе",
    aboutFeature3Desc: "Работаем в районах Сино, Фирдавси, Шохмансур, Исмоили Сомони и пригороде.",
    aboutFeature4Title: "Поддержка 24/7",
    aboutFeature4Desc: "Аварийный мастер приедет даже ночью. Служба поддержки работает круглосуточно.",

    // How it works
    howItWorksTitle: "Как вызвать мастера — 3 простых шага",
    howItWorksStep1Title: "Выберите услугу",
    howItWorksStep1Desc: "Укажите, что нужно сделать: починить кран, установить розетку, собрать мебель.",
    howItWorksStep2Title: "Опишите задачу",
    howItWorksStep2Desc: "Добавьте адрес в Душанбе, телефон и удобное время — мастер подготовится заранее.",
    howItWorksStep3Title: "Мастер приедет",
    howItWorksStep3Desc: "Проверенный специалист приедет к вам домой и выполнит работу качественно.",
    howItWorksFooter: "Без лишних звонков. Заказ онлайн за 2 минуты.",

    // Categories
    categoriesTitle: "Услуги мастеров в Душанбе",
    categoriesDescription: "Выберите категорию и закажите мастера. Все цены в сомони.",
    categoryElectric: "Электрика",
    categoryPlumbing: "Сантехника",
    categoryCleaning: "Уборка",
    categoryFurniture: "Сборка мебели",
    categoryRenovation: "Отделка",
    categorySecurity: "Видеонаблюдение",
    categoryWelding: "Сварка",
    categoryRepair: "Ремонт техники",
    categorySmartHome: "Умный дом",
    categoryGarage: "Подвалы и гаражи",
    categoryTurnkey: "Ремонт под ключ",
    categoryOther: "Другие услуги",
    categoryEmergency: "Аварийный мастер 24/7",
    categoryEmergencyBadge: "Срочно",
    categoryPriceFrom: "аз",
    categoryOrderButton: "Вызвать мастера",
    categoryChooseServices: "Выбрать услуги",

    // Contacts
    contactsTitle: "Свяжитесь с нами",
    contactsDescription: "Звоните, пишите в WhatsApp или Telegram — мы на связи 24/7.",
    contactsPhone: "Телефон",
    contactsEmail: "Почта",
    contactsWorkHours: "Режим работы",
    contactsWorkHoursValue: "24/7 — круглосуточно",

    // Become Master
    becomeMasterTitle: "Станьте мастером в Душанбе",
    becomeMasterSubtitle: "Присоединяйтесь к команде Мастер Час — получайте заказы каждый день по всему Душанбе",
    becomeMasterBenefit1: "Заказы каждый день",
    becomeMasterBenefit2: "Свободный график",
    becomeMasterBenefit3: "Оплата сразу после работы",
    becomeMasterBenefit4: "Поддержка от команды 24/7",
    becomeMasterFormTitle: "Оставить заявку",
    becomeMasterFormName: "Ваше имя",
    becomeMasterFormPhone: "Телефон (+992...)",
    becomeMasterFormSpecialty: "Ваша специальность (электрик, сантехник...)",
    becomeMasterFormExperience: "Опыт работы (лет)",
    becomeMasterFormSubmit: "Отправить заявку",
    becomeMasterFormSuccess: "Раҳмат! Мы свяжемся с вами в ближайшее время.",

    // Services / Price list
    servicesTitle: "Прайс-лист услуг",
    servicesSubtitle: "Все цены в сомони. Точная стоимость — после осмотра мастером.",
    serviceElectric: "Электрика",
    servicePlumbing: "Сантехника",
    serviceCleaning: "Уборка",
    serviceFurniture: "Сборка мебели",
    serviceRenovation: "Отделка",
    serviceSecurity: "Видеонаблюдение",
    serviceWelding: "Сварка",
    serviceBasement: "Подвалы и гаражи",
    serviceTurnkey: "Ремонт под ключ",
    serviceRepair: "Ремонт техники",
    serviceSmartHome: "Умный дом",
    serviceOther: "Другие услуги",

    // Forms
    formName: "Ваше имя",
    formPhone: "Телефон (+992...)",
    formService: "Выберите услугу",
    formDistrict: "Район Душанбе",
    formComment: "Опишите задачу (необязательно)",
    formSubmit: "Отправить заявку",
    formSuccess: "Раҳмат! Мы скоро свяжемся с вами",

    // Districts
    districtSino: "Сино",
    districtFirdausi: "Фирдавси",
    districtShomansur: "Шохмансур",
    districtIsmoili: "Исмоили Сомони",

    // Footer
    footerAboutText: "Мастер Час — сервис вызова мастеров на дом в Душанбе. Электрика, сантехника, уборка, ремонт — быстро и по честным ценам.",
    footerContacts: "Контакты",
    footerDistricts: "Районы Душанбе",
    footerRights: "© 2025 Мастер Час. Душанбе, Тоҷикистон. Ҳамаи ҳуқуқҳо ҳифз шудаанд.",
    footerServices: "Услуги",
    footerSubscriptions: "Тарифы",
    footerBecomeMaster: "Стать мастером",
    footerForBusiness: "Для бизнеса",
    footerPrivacy: "Конфиденциальность",
    footerTerms: "Условия",

    // Common
    viewAllCategories: "Все категории услуг",
    learnMore: "Подробнее",
    qualityGuarantee: "Кафолати сифат",
    qualityGuaranteeDesc: "Если работа не устроит — мастер вернётся и исправит бесплатно",
    step: "Қадам",
    orderModalTitle: "Вызвать мастера",
    orderModalDesc: "Заполните форму — мы подберём мастера в вашем районе",
    orderModalSubmit: "Отправить",
    orderModalSuccess: "Дархост қабул шуд! Мы скоро свяжемся.",

    // ===== SHOP =====
    shopTitle: "Магазин Master Chas",
    shopSubtitle: "Товары для ремонта, дома и установки — с доставкой и возможностью заказать мастера для монтажа",
    shopMarketplace: "Маркетплейс товаров",
    shopGoToCatalog: "Перейти в каталог",
    shopFindMaster: "Найти мастера для установки",
    shopProducts: "товаров",
    shopCategories: "категорий",
    shopDelivery: "Доставка",
    shopCart: "Корзина",
    shopCategoryTitle: "Категории товаров",
    shopCategorySubtitle: "Выберите нужную категорию",
    shopDiscounts: "Акции и скидки",
    shopDiscountsSubtitle: "Успейте купить по выгодной цене",
    shopPopular: "Популярные товары",
    shopPopularSubtitle: "Самые востребованные товары",
    shopProductInstall: "Товар + Установка",
    shopBuyWithInstall: "Купите товар и закажите установку мастером",
    shopInstallDesc: "Не нужно искать специалиста отдельно — выберите товар, добавьте установку, и мы пришлём проверенного мастера",
    shopInstallFrom: "Установка от",
    shopMasterInstall: "Установка мастером",
    shopBuyWithInstallBtn: "Купить с установкой",
    shopRecommended: "Рекомендуем",
    shopRecommendedSubtitle: "Лучшие товары по рейтингу и отзывам",
    shopAllProducts: "Все товары",
    shopTrustTitle: "Почему покупать у Master Chas?",
    shopTrustSubtitle: "Мы объединяем магазин и сервис мастеров — всё в одном месте",
    shopTrustMasters: "Проверенные мастера",
    shopTrustMastersDesc: "Все мастера проходят проверку",
    shopTrustGuarantee: "Гарантия работ",
    shopTrustGuaranteeDesc: "Гарантия на все услуги",
    shopTrustDelivery: "Быстрая доставка",
    shopTrustDeliveryDesc: "Доставка по Душанбе",
    shopTrustSupport: "Поддержка 24/7",
    shopTrustSupportDesc: "Всегда на связи",
    shopNeedHelp: "Нужна помощь с выбором? Позвоните нам",
    shopSearchPlaceholder: "Найдите товар для дома и ремонта...",
    shopSearchResults: "Результаты поиска",
    shopNoResults: "Ничего не найдено",
    shopNoResultsHint: "Попробуйте другой запрос или посмотрите популярные товары",
    shopFromMaster: "От мастера",
    shopInstallBadge: "+ установка",
    shopOutOfStock: "Нет в наличии",
    shopInStock: "В наличии",
    shopAddToCart: "В корзину",
    shopBuyNow: "Купить сейчас",
    shopDetails: "Подробнее",
    shopPrice: "Цена",
    shopOldPrice: "Старая цена",
    shopRating: "Рейтинг",
    shopReviews: "отзывов",
    shopSpecs: "Характеристики",
    shopQuantity: "Количество",
    shopTotal: "Итого",
    shopProduct: "Товар",
    shopPcs: "шт.",
    shopNeedInstall: "Нужна установка мастером?",
    shopProfInstall: "Профессиональная установка",
    shopBackToShop: "Вернуться в магазин",
    shopProductNotFound: "Товар не найден",
    shopSimilar: "Похожие товары",
    shopByPopularity: "По популярности",
    shopPriceAsc: "Цена ↑",
    shopPriceDesc: "Цена ↓",
    shopByRating: "По рейтингу",
    shopProductsCount: "товаров",
    shopCategory: "Категория",
    shopRecentSearches: "Недавние запросы",
    shopPopularSearches: "Популярные запросы",
    shopClearSearch: "Очистить",
    shopFilterCategory: "Категория",
    shopFilterPrice: "Цена",
    shopFilterAvailability: "Наличие",
    shopFilterRating: "Рейтинг",
    shopAllCategories: "Все категории",
    shopPriceRange: "Диапазон цен",
    shopInStockOnly: "Только в наличии",
    shopApplyFilters: "Применить",
    shopResetFilters: "Сбросить",

    // ===== ORDER STATUSES =====
    statusNew: "Новый",
    statusAccepted: "Принят",
    statusAssigned: "Назначен",
    statusOnTheWay: "В пути",
    statusArrived: "Прибыл",
    statusInProgress: "В работе",
    statusCompleted: "Завершён",
    statusCancelled: "Отменён",
    statusPending: "Ожидает",
    statusApproved: "Одобрен",
    statusRejected: "Отклонён",
    statusPaid: "Оплачен",
    statusUnpaid: "Не оплачен",

    // ===== DASHBOARD COMMON =====
    dashOverview: "Обзор",
    dashOrders: "Заказы",
    dashActiveOrders: "Активные заказы",
    dashCompletedOrders: "Завершённые заказы",
    dashEarnings: "Заработок",
    dashReviews: "Отзывы",
    dashPortfolio: "Портфолио",
    dashProfile: "Профиль",
    dashNotifications: "Уведомления",
    dashSchedule: "Расписание",
    dashMyProducts: "Мои товары",
    dashUsers: "Пользователи",
    dashMasters: "Мастера",
    dashApplications: "Заявки мастеров",
    dashShop: "Магазин",
    dashAnalytics: "Аналитика",
    dashSettings: "Настройки",
    dashToday: "Сегодня",
    dashWeek: "Неделя",
    dashMonth: "Месяц",
    dashTotal: "Всего",
    dashRevenue: "Доход",
    dashCommission: "Комиссия",
    dashPayout: "Выплата",
    dashNoData: "Нет данных",
    dashSearch: "Поиск...",

    // ===== CART =====
    cartTitle: "Корзина",
    cartEmpty: "Ваша корзина пуста",
    cartEmptyHint: "Перейдите в магазин, чтобы добавить товары",
    cartGoToShop: "Перейти в магазин",
    cartRemove: "Удалить",
    cartCheckout: "Оформить заказ",
    cartDeliveryAddress: "Адрес доставки",
    cartPhone: "Телефон",
    cartName: "Ваше имя",
    cartComments: "Комментарий к заказу",
    cartOrderSuccess: "Заказ оформлен!",
    cartOrderSuccessDesc: "Мы свяжемся с вами для подтверждения",

    // ===== AI MATCH =====
    aiMatchTitle: "AI подбор мастера",
    aiMatchDesc: "Опишите вашу проблему — мы подберём лучшего мастера",
    aiMatchPlaceholder: "Опишите проблему...",
    aiMatchSearch: "Подобрать мастера",
    aiMatchLoading: "Ищем лучшего мастера...",
    aiMatchBestChoice: "Лучший выбор",
    aiMatchClosest: "Ближе всех",
    aiMatchHighRating: "Высокий рейтинг",
    aiMatchFastArrival: "Быстрый выезд",
    aiMatchChoose: "Выбрать мастера",

    // ===== AUTH =====
    authSignIn: "Войти",
    authSignUp: "Зарегистрироваться",
    authEmail: "Email",
    authPassword: "Пароль",
    authFullName: "Полное имя",
    authForgotPassword: "Забыли пароль?",
    authNoAccount: "Нет аккаунта?",
    authHaveAccount: "Уже есть аккаунт?",

    // ===== MISC =====
    loading: "Загрузка...",
    error: "Ошибка",
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    edit: "Редактировать",
    add: "Добавить",
    close: "Закрыть",
    confirm: "Подтвердить",
    back: "Назад",
    next: "Далее",
    yes: "Да",
    no: "Нет",
    somoni: "сомонӣ",
    som: "с.",
  },
  tj: {
    navAbout: "Дар бораи мо",
    navCategories: "Хидматҳо",
    navMasters: "Устоҳо",
    navHowItWorks: "Тарзи кор",
    navContacts: "Тамос",
    navBecomeMaster: "Усто шавед",
    navShop: "Мағоза",
    login: "Даромадан",
    logout: "Баромадан",
    cabinet: "Кабинет",
    admin: "Админ",
    masterCabinet: "Кабинети усто",
    clientCabinet: "Кабинети ман",
    subscription: "Обуна",
    heroTitle: "Усто ба хонаатон меояд",
    heroSubtitle: "Устоони боэътимод • Баромадан аз 30 дақиқа • Кафолати кор",
    heroDescription: "Мастер Час — хидмати даъвати усто ба хона дар Душанбе. Барқ, сантехника, тозакунӣ, таъмири техника ва дигар хидматҳо — зуд, боэътимод, бо нархҳои одилона дар сомонӣ.",
    heroOrderButton: "Усто даъват кунед",
    heroEmergencyButton: "🚨 Устои таъҷилӣ 24/7",
    heroEmergencySubtext: "баромадан 30–60 дақиқа дар Душанбе",
    trustTime: "Дар 1 соат",
    trustTimeDesc: "усто назди шумо меояд",
    trustRating: "4.9",
    trustRatingDesc: "рейтинги миёнаи устоон",
    trustOrders: "5000+",
    trustOrdersDesc: "фармоишҳо дар Душанбе иҷро шудаанд",
    aboutTitle: "Мастер Час — хидмати устоон дар Душанбе",
    aboutDescription: "Мо ба сокинони Душанбе кӯмак мекунем, ки зуд устои боэътимод пайдо кунанд — аз насби розетка то таъмири пурра.",
    aboutFeature1Title: "Устоони тасдиқшуда",
    aboutFeature1Desc: "Ҳар як усто тафтиши ҳуҷҷатҳо ва малакаро мегузарад.",
    aboutFeature2Title: "Нархҳо дар сомонӣ",
    aboutFeature2Desc: "Нархҳои шаффоф бе пардохтҳои пинҳонӣ.",
    aboutFeature3Title: "Баромадан дар тамоми Душанбе",
    aboutFeature3Desc: "Дар ноҳияҳои Сино, Фирдавсӣ, Шоҳмансур, Исмоилӣ Сомонӣ кор мекунем.",
    aboutFeature4Title: "Дастгирии 24/7",
    aboutFeature4Desc: "Устои таъҷилӣ ҳатто шабона меояд.",
    howItWorksTitle: "Чӣ тавр усторо даъват кардан — 3 қадами содда",
    howItWorksStep1Title: "Хидматро интихоб кунед",
    howItWorksStep1Desc: "Нишон диҳед, ки чӣ кор бояд кард.",
    howItWorksStep2Title: "Вазифаро тавсиф кунед",
    howItWorksStep2Desc: "Суроға дар Душанбе, телефон ва вақти муносибро илова кунед.",
    howItWorksStep3Title: "Усто меояд",
    howItWorksStep3Desc: "Мутахассиси тасдиқшуда ба хонаатон меояд.",
    howItWorksFooter: "Бе зангҳои зиёдатӣ. Фармоиш дар 2 дақиқа онлайн.",
    categoriesTitle: "Хидматҳои устоон дар Душанбе",
    categoriesDescription: "Категорияро интихоб кунед ва усторо даъват кунед.",
    categoryElectric: "Барқ",
    categoryPlumbing: "Сантехника",
    categoryCleaning: "Тозакунӣ",
    categoryFurniture: "Ҷамъкунии мебел",
    categoryRenovation: "Ороиш",
    categorySecurity: "Видеоназорат",
    categoryWelding: "Ҷӯшкорӣ",
    categoryRepair: "Таъмири техника",
    categorySmartHome: "Хонаи зиракона",
    categoryGarage: "Зеризамин ва гаражҳо",
    categoryTurnkey: "Таъмири пурра",
    categoryOther: "Хидматҳои дигар",
    categoryEmergency: "Устои таъҷилӣ 24/7",
    categoryEmergencyBadge: "Зудӣ",
    categoryPriceFrom: "аз",
    categoryOrderButton: "Усто даъват кунед",
    categoryChooseServices: "Хидматро интихоб кунед",
    contactsTitle: "Бо мо тамос гиред",
    contactsDescription: "Занг занед, ба WhatsApp ё Telegram нависед — мо 24/7 дар тамос ҳастем.",
    contactsPhone: "Телефон",
    contactsEmail: "Почта",
    contactsWorkHours: "Тартиби корӣ",
    contactsWorkHoursValue: "24/7 — шабонарӯзӣ",
    becomeMasterTitle: "Дар Душанбе усто шавед",
    becomeMasterSubtitle: "Ба дастаи Мастер Час ҳамроҳ шавед — ҳар рӯз фармоиш гиред",
    becomeMasterBenefit1: "Ҳар рӯз фармоишҳо",
    becomeMasterBenefit2: "Ҷадвали озод",
    becomeMasterBenefit3: "Пардохт фавран пас аз кор",
    becomeMasterBenefit4: "Дастгирии дастаи 24/7",
    becomeMasterFormTitle: "Дархост гузоред",
    becomeMasterFormName: "Номи шумо",
    becomeMasterFormPhone: "Телефон (+992...)",
    becomeMasterFormSpecialty: "Ихтисоси шумо",
    becomeMasterFormExperience: "Таҷрибаи кор (сол)",
    becomeMasterFormSubmit: "Фиристодани дархост",
    becomeMasterFormSuccess: "Раҳмат! Мо зуд бо шумо тамос мегирем.",
    servicesTitle: "Нархнома",
    servicesSubtitle: "Ҳамаи нархҳо дар сомонӣ.",
    serviceElectric: "Барқкорӣ",
    servicePlumbing: "Сантехника",
    serviceCleaning: "Тозакунӣ",
    serviceFurniture: "Ҷамъкунии мебел",
    serviceRenovation: "Ороиш",
    serviceSecurity: "Видеоназорат",
    serviceWelding: "Ҷӯшкорӣ",
    serviceBasement: "Зеризамин ва гаражҳо",
    serviceTurnkey: "Таъмири пурра",
    serviceRepair: "Таъмири техника",
    serviceSmartHome: "Хонаи зиракона",
    serviceOther: "Хидматҳои дигар",
    formName: "Номи шумо",
    formPhone: "Телефон (+992...)",
    formService: "Хидматро интихоб кунед",
    formDistrict: "Ноҳияи Душанбе",
    formComment: "Вазифаро тавсиф кунед (ихтиёрӣ)",
    formSubmit: "Фиристодани дархост",
    formSuccess: "Раҳмат! Мо зуд бо шумо тамос мегирем",
    districtSino: "Сино",
    districtFirdausi: "Фирдавсӣ",
    districtShomansur: "Шоҳмансур",
    districtIsmoili: "Исмоилӣ Сомонӣ",
    footerAboutText: "Мастер Час — хидмати даъвати усто ба хона дар Душанбе.",
    footerContacts: "Тамос",
    footerDistricts: "Ноҳияҳои Душанбе",
    footerRights: "© 2025 Мастер Час. Душанбе, Тоҷикистон.",
    footerServices: "Хидматҳо",
    footerSubscriptions: "Тарифҳо",
    footerBecomeMaster: "Усто шавед",
    footerForBusiness: "Барои бизнес",
    footerPrivacy: "Сиёсати махфият",
    footerTerms: "Шартҳои истифода",
    viewAllCategories: "Ҳамаи категорияҳоро дидан",
    learnMore: "Бештар",
    qualityGuarantee: "Кафолати сифат",
    qualityGuaranteeDesc: "Агар кор маъқул нашавад — усто бармегардад ва ройгон ислоҳ мекунад",
    step: "Қадам",
    orderModalTitle: "Усто даъват кунед",
    orderModalDesc: "Формаро пур кунед — мо дар ноҳияи шумо усторо интихоб мекунем",
    orderModalSubmit: "Фиристодан",
    orderModalSuccess: "Дархост қабул шуд! Мо зуд тамос мегирем.",

    // Shop
    shopTitle: "Мағозаи Master Chas",
    shopSubtitle: "Молҳо барои таъмир, хона ва насб — бо интиқол ва имконияти фармоиши усто",
    shopMarketplace: "Маркетплейси молҳо",
    shopGoToCatalog: "Ба каталог гузаред",
    shopFindMaster: "Усто барои насб ёбед",
    shopProducts: "мол",
    shopCategories: "категория",
    shopDelivery: "Интиқол",
    shopCart: "Сабад",
    shopCategoryTitle: "Категорияҳои молҳо",
    shopCategorySubtitle: "Категорияи лозимро интихоб кунед",
    shopDiscounts: "Тахфифот",
    shopDiscountsSubtitle: "Бо нархи муносиб харед",
    shopPopular: "Молҳои маъмул",
    shopPopularSubtitle: "Молҳои серталаб",
    shopProductInstall: "Мол + Насб",
    shopBuyWithInstall: "Мол харед ва насби усторо фармоиш диҳед",
    shopInstallDesc: "Мутахассисро алоҳида ҷустуҷӯ накунед — молро интихоб кунед, насбро илова кунед",
    shopInstallFrom: "Насб аз",
    shopMasterInstall: "Насб аз тарафи усто",
    shopBuyWithInstallBtn: "Бо насб харед",
    shopRecommended: "Тавсия мекунем",
    shopRecommendedSubtitle: "Беҳтарин молҳо аз рӯи рейтинг",
    shopAllProducts: "Ҳамаи молҳо",
    shopTrustTitle: "Чаро аз Master Chas харед?",
    shopTrustSubtitle: "Мо мағоза ва хидмати устоонро дар як ҷо муттаҳид мекунем",
    shopTrustMasters: "Устоони тасдиқшуда",
    shopTrustMastersDesc: "Ҳамаи устоон тафтиш мешаванд",
    shopTrustGuarantee: "Кафолати кор",
    shopTrustGuaranteeDesc: "Кафолат ба ҳамаи хидматҳо",
    shopTrustDelivery: "Интиқоли зуд",
    shopTrustDeliveryDesc: "Интиқол дар Душанбе",
    shopTrustSupport: "Дастгирии 24/7",
    shopTrustSupportDesc: "Ҳамеша дар тамос",
    shopNeedHelp: "Барои интихоб кӯмак лозим аст? Ба мо занг занед",
    shopSearchPlaceholder: "Молро барои хона ва таъмир ёбед...",
    shopSearchResults: "Натиҷаҳои ҷустуҷӯ",
    shopNoResults: "Чизе ёфт нашуд",
    shopNoResultsHint: "Дархости дигарро озмоед ё молҳои маъмулро бинед",
    shopFromMaster: "Аз усто",
    shopInstallBadge: "+ насб",
    shopOutOfStock: "Нест дар анбор",
    shopInStock: "Дар анбор",
    shopAddToCart: "Ба сабад",
    shopBuyNow: "Ҳозир харед",
    shopDetails: "Муфассал",
    shopPrice: "Нарх",
    shopOldPrice: "Нархи кӯҳна",
    shopRating: "Рейтинг",
    shopReviews: "тақриз",
    shopSpecs: "Хусусиятҳо",
    shopQuantity: "Миқдор",
    shopTotal: "Ҳамагӣ",
    shopProduct: "Мол",
    shopPcs: "дона",
    shopNeedInstall: "Насби усто лозим аст?",
    shopProfInstall: "Насби касбӣ",
    shopBackToShop: "Ба мағоза баргардед",
    shopProductNotFound: "Мол ёфт нашуд",
    shopSimilar: "Молҳои монанд",
    shopByPopularity: "Аз рӯи маъмулият",
    shopPriceAsc: "Нарх ↑",
    shopPriceDesc: "Нарх ↓",
    shopByRating: "Аз рӯи рейтинг",
    shopProductsCount: "мол",
    shopCategory: "Категория",
    shopRecentSearches: "Дархостҳои охирин",
    shopPopularSearches: "Дархостҳои маъмул",
    shopClearSearch: "Тоза кардан",
    shopFilterCategory: "Категория",
    shopFilterPrice: "Нарх",
    shopFilterAvailability: "Мавҷудият",
    shopFilterRating: "Рейтинг",
    shopAllCategories: "Ҳамаи категорияҳо",
    shopPriceRange: "Диапазони нарх",
    shopInStockOnly: "Танҳо дар анбор",
    shopApplyFilters: "Татбиқ кардан",
    shopResetFilters: "Бозгашт",

    // Statuses
    statusNew: "Нав",
    statusAccepted: "Қабул шуд",
    statusAssigned: "Таъин шуд",
    statusOnTheWay: "Дар роҳ",
    statusArrived: "Расид",
    statusInProgress: "Дар ҷараён",
    statusCompleted: "Анҷом ёфт",
    statusCancelled: "Бекор шуд",
    statusPending: "Интизорӣ",
    statusApproved: "Тасдиқ шуд",
    statusRejected: "Рад шуд",
    statusPaid: "Пардохт шуд",
    statusUnpaid: "Пардохт нашуд",

    // Dashboard
    dashOverview: "Хулоса",
    dashOrders: "Фармоишҳо",
    dashActiveOrders: "Фармоишҳои фаъол",
    dashCompletedOrders: "Фармоишҳои анҷомёфта",
    dashEarnings: "Даромад",
    dashReviews: "Тақризҳо",
    dashPortfolio: "Портфолио",
    dashProfile: "Профил",
    dashNotifications: "Огоҳиҳо",
    dashSchedule: "Ҷадвал",
    dashMyProducts: "Молҳои ман",
    dashUsers: "Корбарон",
    dashMasters: "Устоҳо",
    dashApplications: "Дархостҳои устоон",
    dashShop: "Мағоза",
    dashAnalytics: "Таҳлил",
    dashSettings: "Танзимот",
    dashToday: "Имрӯз",
    dashWeek: "Ҳафта",
    dashMonth: "Моҳ",
    dashTotal: "Ҳамагӣ",
    dashRevenue: "Даромад",
    dashCommission: "Комиссия",
    dashPayout: "Пардохт",
    dashNoData: "Маълумот нест",
    dashSearch: "Ҷустуҷӯ...",

    // Cart
    cartTitle: "Сабад",
    cartEmpty: "Сабади шумо холӣ аст",
    cartEmptyHint: "Ба мағоза гузаред ва молҳо илова кунед",
    cartGoToShop: "Ба мағоза гузаред",
    cartRemove: "Нест кардан",
    cartCheckout: "Фармоиш додан",
    cartDeliveryAddress: "Суроғаи интиқол",
    cartPhone: "Телефон",
    cartName: "Номи шумо",
    cartComments: "Шарҳ ба фармоиш",
    cartOrderSuccess: "Фармоиш қабул шуд!",
    cartOrderSuccessDesc: "Мо бо шумо тамос мегирем",

    // AI
    aiMatchTitle: "AI интихоби усто",
    aiMatchDesc: "Мушкилии худро тавсиф кунед — мо беҳтарин усторо пайдо мекунем",
    aiMatchPlaceholder: "Мушкилиро тавсиф кунед...",
    aiMatchSearch: "Усторо пайдо кунед",
    aiMatchLoading: "Беҳтарин усторо меҷӯем...",
    aiMatchBestChoice: "Беҳтарин интихоб",
    aiMatchClosest: "Наздиктарин",
    aiMatchHighRating: "Рейтинги баланд",
    aiMatchFastArrival: "Баромадани зуд",
    aiMatchChoose: "Усторо интихоб кунед",

    // Auth
    authSignIn: "Даромадан",
    authSignUp: "Бақайдгирӣ",
    authEmail: "Email",
    authPassword: "Рамз",
    authFullName: "Номи пурра",
    authForgotPassword: "Рамзро фаромӯш кардед?",
    authNoAccount: "Аккаунт надоред?",
    authHaveAccount: "Аккаунт доред?",

    // Misc
    loading: "Боркунӣ...",
    error: "Хатогӣ",
    save: "Нигоҳ доштан",
    cancel: "Бекор кардан",
    delete: "Нест кардан",
    edit: "Таҳрир",
    add: "Илова кардан",
    close: "Пӯшидан",
    confirm: "Тасдиқ кардан",
    back: "Бозгашт",
    next: "Пеш",
    yes: "Ҳа",
    no: "Не",
    somoni: "сомонӣ",
    som: "с.",
  },
  en: {
    navAbout: "About Us",
    navCategories: "Services",
    navMasters: "Masters",
    navHowItWorks: "How It Works",
    navContacts: "Contacts",
    navBecomeMaster: "Become a Master",
    navShop: "Shop",
    login: "Login",
    logout: "Logout",
    cabinet: "Dashboard",
    admin: "Admin",
    masterCabinet: "Master Dashboard",
    clientCabinet: "My Dashboard",
    subscription: "Subscription",
    heroTitle: "Your master will arrive today",
    heroSubtitle: "Verified masters • Arrival from 30 min • Work guarantee",
    heroDescription: "Master Chas is a home service marketplace in Dushanbe. Electrical, plumbing, cleaning, appliance repair and more — fast, reliable, at fair prices in somoni.",
    heroOrderButton: "Call a Master",
    heroEmergencyButton: "🚨 Emergency Master 24/7",
    heroEmergencySubtext: "arrival 30–60 min in Dushanbe",
    trustTime: "Within 1 hour",
    trustTimeDesc: "master arrives at your door",
    trustRating: "4.9",
    trustRatingDesc: "average master rating",
    trustOrders: "5000+",
    trustOrdersDesc: "orders completed in Dushanbe",
    aboutTitle: "Master Chas — Home Service in Dushanbe",
    aboutDescription: "We help Dushanbe residents quickly find a verified master for any household task.",
    aboutFeature1Title: "Verified Masters",
    aboutFeature1Desc: "Every master undergoes document and skill verification.",
    aboutFeature2Title: "Prices in Somoni",
    aboutFeature2Desc: "Transparent prices with no hidden fees.",
    aboutFeature3Title: "All of Dushanbe",
    aboutFeature3Desc: "We serve Sino, Firdavsi, Shohmansur, Ismoili Somoni districts.",
    aboutFeature4Title: "24/7 Support",
    aboutFeature4Desc: "Emergency master available even at night.",
    howItWorksTitle: "How to call a master — 3 simple steps",
    howItWorksStep1Title: "Choose a service",
    howItWorksStep1Desc: "Tell us what needs to be done.",
    howItWorksStep2Title: "Describe the task",
    howItWorksStep2Desc: "Add your address, phone number, and preferred time.",
    howItWorksStep3Title: "Master arrives",
    howItWorksStep3Desc: "A verified specialist will come to your home.",
    howItWorksFooter: "No extra calls. Order online in 2 minutes.",
    categoriesTitle: "Home Services in Dushanbe",
    categoriesDescription: "Choose a category and call a master. All prices in somoni.",
    categoryElectric: "Electrical",
    categoryPlumbing: "Plumbing",
    categoryCleaning: "Cleaning",
    categoryFurniture: "Furniture Assembly",
    categoryRenovation: "Finishing",
    categorySecurity: "CCTV",
    categoryWelding: "Welding",
    categoryRepair: "Appliance Repair",
    categorySmartHome: "Smart Home",
    categoryGarage: "Basements & Garages",
    categoryTurnkey: "Turnkey Renovation",
    categoryOther: "Other Services",
    categoryEmergency: "Emergency Master 24/7",
    categoryEmergencyBadge: "Urgent",
    categoryPriceFrom: "from",
    categoryOrderButton: "Call a Master",
    categoryChooseServices: "Choose Services",
    contactsTitle: "Contact Us",
    contactsDescription: "Call, write on WhatsApp or Telegram — we're available 24/7.",
    contactsPhone: "Phone",
    contactsEmail: "Email",
    contactsWorkHours: "Working hours",
    contactsWorkHoursValue: "24/7 — around the clock",
    becomeMasterTitle: "Become a Master in Dushanbe",
    becomeMasterSubtitle: "Join the Master Chas team — get orders every day",
    becomeMasterBenefit1: "Daily orders",
    becomeMasterBenefit2: "Flexible schedule",
    becomeMasterBenefit3: "Payment right after the job",
    becomeMasterBenefit4: "Team support 24/7",
    becomeMasterFormTitle: "Submit Application",
    becomeMasterFormName: "Your name",
    becomeMasterFormPhone: "Phone (+992...)",
    becomeMasterFormSpecialty: "Your specialty",
    becomeMasterFormExperience: "Work experience (years)",
    becomeMasterFormSubmit: "Submit Application",
    becomeMasterFormSuccess: "Thank you! We will contact you soon.",
    servicesTitle: "Price List",
    servicesSubtitle: "All prices in somoni. Final cost confirmed after inspection.",
    serviceElectric: "Electrical",
    servicePlumbing: "Plumbing",
    serviceCleaning: "Cleaning",
    serviceFurniture: "Furniture Assembly",
    serviceRenovation: "Finishing",
    serviceSecurity: "CCTV",
    serviceWelding: "Welding",
    serviceBasement: "Basements & Garages",
    serviceTurnkey: "Turnkey Renovation",
    serviceRepair: "Appliance Repair",
    serviceSmartHome: "Smart Home",
    serviceOther: "Other Services",
    formName: "Your Name",
    formPhone: "Phone (+992...)",
    formService: "Select Service",
    formDistrict: "Dushanbe District",
    formComment: "Describe the task (optional)",
    formSubmit: "Submit Request",
    formSuccess: "Thank you! We'll contact you soon",
    districtSino: "Sino",
    districtFirdausi: "Firdavsi",
    districtShomansur: "Shohmansur",
    districtIsmoili: "Ismoili Somoni",
    footerAboutText: "Master Chas — home service marketplace in Dushanbe.",
    footerContacts: "Contacts",
    footerDistricts: "Dushanbe Districts",
    footerRights: "© 2025 Master Chas. Dushanbe, Tajikistan. All rights reserved.",
    footerServices: "Services",
    footerSubscriptions: "Plans",
    footerBecomeMaster: "Become a Master",
    footerForBusiness: "For Business",
    footerPrivacy: "Privacy Policy",
    footerTerms: "Terms of Service",
    viewAllCategories: "View all service categories",
    learnMore: "Learn more",
    qualityGuarantee: "Quality Guarantee",
    qualityGuaranteeDesc: "If the work doesn't satisfy — the master will return and fix it for free",
    step: "Step",
    orderModalTitle: "Call a Master",
    orderModalDesc: "Fill out the form — we'll find a master in your area",
    orderModalSubmit: "Submit",
    orderModalSuccess: "Request accepted! We'll contact you soon.",

    // Shop
    shopTitle: "Master Chas Shop",
    shopSubtitle: "Products for repair, home and installation — with delivery and master installation option",
    shopMarketplace: "Product Marketplace",
    shopGoToCatalog: "Browse Catalog",
    shopFindMaster: "Find a master for installation",
    shopProducts: "products",
    shopCategories: "categories",
    shopDelivery: "Delivery",
    shopCart: "Cart",
    shopCategoryTitle: "Product Categories",
    shopCategorySubtitle: "Choose the right category",
    shopDiscounts: "Sales & Discounts",
    shopDiscountsSubtitle: "Buy at the best price",
    shopPopular: "Popular Products",
    shopPopularSubtitle: "Most in-demand products",
    shopProductInstall: "Product + Installation",
    shopBuyWithInstall: "Buy a product and order master installation",
    shopInstallDesc: "No need to find a specialist separately — choose a product, add installation, and we'll send a verified master",
    shopInstallFrom: "Installation from",
    shopMasterInstall: "Master installation",
    shopBuyWithInstallBtn: "Buy with installation",
    shopRecommended: "Recommended",
    shopRecommendedSubtitle: "Best products by rating and reviews",
    shopAllProducts: "All products",
    shopTrustTitle: "Why buy from Master Chas?",
    shopTrustSubtitle: "We combine a shop and master services — all in one place",
    shopTrustMasters: "Verified Masters",
    shopTrustMastersDesc: "All masters are verified",
    shopTrustGuarantee: "Work Guarantee",
    shopTrustGuaranteeDesc: "Guarantee on all services",
    shopTrustDelivery: "Fast Delivery",
    shopTrustDeliveryDesc: "Delivery in Dushanbe",
    shopTrustSupport: "24/7 Support",
    shopTrustSupportDesc: "Always available",
    shopNeedHelp: "Need help choosing? Call us",
    shopSearchPlaceholder: "Find products for home and repair...",
    shopSearchResults: "Search Results",
    shopNoResults: "Nothing found",
    shopNoResultsHint: "Try a different query or browse popular products",
    shopFromMaster: "From master",
    shopInstallBadge: "+ installation",
    shopOutOfStock: "Out of stock",
    shopInStock: "In stock",
    shopAddToCart: "Add to cart",
    shopBuyNow: "Buy now",
    shopDetails: "Details",
    shopPrice: "Price",
    shopOldPrice: "Old price",
    shopRating: "Rating",
    shopReviews: "reviews",
    shopSpecs: "Specifications",
    shopQuantity: "Quantity",
    shopTotal: "Total",
    shopProduct: "Product",
    shopPcs: "pcs",
    shopNeedInstall: "Need master installation?",
    shopProfInstall: "Professional installation",
    shopBackToShop: "Back to shop",
    shopProductNotFound: "Product not found",
    shopSimilar: "Similar products",
    shopByPopularity: "By popularity",
    shopPriceAsc: "Price ↑",
    shopPriceDesc: "Price ↓",
    shopByRating: "By rating",
    shopProductsCount: "products",
    shopCategory: "Category",
    shopRecentSearches: "Recent searches",
    shopPopularSearches: "Popular searches",
    shopClearSearch: "Clear",
    shopFilterCategory: "Category",
    shopFilterPrice: "Price",
    shopFilterAvailability: "Availability",
    shopFilterRating: "Rating",
    shopAllCategories: "All categories",
    shopPriceRange: "Price range",
    shopInStockOnly: "In stock only",
    shopApplyFilters: "Apply",
    shopResetFilters: "Reset",

    // Statuses
    statusNew: "New",
    statusAccepted: "Accepted",
    statusAssigned: "Assigned",
    statusOnTheWay: "On the way",
    statusArrived: "Arrived",
    statusInProgress: "In progress",
    statusCompleted: "Completed",
    statusCancelled: "Cancelled",
    statusPending: "Pending",
    statusApproved: "Approved",
    statusRejected: "Rejected",
    statusPaid: "Paid",
    statusUnpaid: "Unpaid",

    // Dashboard
    dashOverview: "Overview",
    dashOrders: "Orders",
    dashActiveOrders: "Active Orders",
    dashCompletedOrders: "Completed Orders",
    dashEarnings: "Earnings",
    dashReviews: "Reviews",
    dashPortfolio: "Portfolio",
    dashProfile: "Profile",
    dashNotifications: "Notifications",
    dashSchedule: "Schedule",
    dashMyProducts: "My Products",
    dashUsers: "Users",
    dashMasters: "Masters",
    dashApplications: "Master Applications",
    dashShop: "Shop",
    dashAnalytics: "Analytics",
    dashSettings: "Settings",
    dashToday: "Today",
    dashWeek: "Week",
    dashMonth: "Month",
    dashTotal: "Total",
    dashRevenue: "Revenue",
    dashCommission: "Commission",
    dashPayout: "Payout",
    dashNoData: "No data",
    dashSearch: "Search...",

    // Cart
    cartTitle: "Cart",
    cartEmpty: "Your cart is empty",
    cartEmptyHint: "Go to the shop to add products",
    cartGoToShop: "Go to shop",
    cartRemove: "Remove",
    cartCheckout: "Checkout",
    cartDeliveryAddress: "Delivery address",
    cartPhone: "Phone",
    cartName: "Your name",
    cartComments: "Order comments",
    cartOrderSuccess: "Order placed!",
    cartOrderSuccessDesc: "We'll contact you for confirmation",

    // AI
    aiMatchTitle: "AI Master Match",
    aiMatchDesc: "Describe your problem — we'll find the best master",
    aiMatchPlaceholder: "Describe the problem...",
    aiMatchSearch: "Find a master",
    aiMatchLoading: "Finding the best master...",
    aiMatchBestChoice: "Best choice",
    aiMatchClosest: "Closest",
    aiMatchHighRating: "High rating",
    aiMatchFastArrival: "Fast arrival",
    aiMatchChoose: "Choose master",

    // Auth
    authSignIn: "Sign In",
    authSignUp: "Sign Up",
    authEmail: "Email",
    authPassword: "Password",
    authFullName: "Full Name",
    authForgotPassword: "Forgot password?",
    authNoAccount: "Don't have an account?",
    authHaveAccount: "Already have an account?",

    // Misc
    loading: "Loading...",
    error: "Error",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    close: "Close",
    confirm: "Confirm",
    back: "Back",
    next: "Next",
    yes: "Yes",
    no: "No",
    somoni: "somoni",
    som: "s.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("mc_lang");
    return (saved === "ru" || saved === "tj" || saved === "en") ? saved : "ru";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("mc_lang", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations["ru"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
