import { createContext, useContext, useState, ReactNode } from "react";

type Language = "ru" | "tj" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ru: {
    navAbout: "О нас",
    navCategories: "Услуги",
    navMasters: "Мастера",
    navHowItWorks: "Как это работает",
    navContacts: "Контакты",
    navBecomeMaster: "Стать мастером",
    login: "Войти",
    logout: "Выйти",
    cabinet: "Кабинет",
    admin: "Админ",
    masterCabinet: "Кабинет мастера",
    clientCabinet: "Мой кабинет",
    subscription: "Подписка",
    heroTitle: "Усто ба хонаатон меояд",
    heroSubtitle: "Устоони тасдиқшуда • Баромадан аз 30 дақиқа • Кафолати кор",
    heroDescription: "Мастер Час — сервис вызова мастеров на дом в Душанбе. Электрика, сантехника, уборка, ремонт техники и другие услуги — быстро, надёжно, по честным ценам в сомони.",
    heroOrderButton: "Вызвать мастера",
    heroEmergencyButton: "🚨 Аварийный мастер 24/7",
    heroEmergencySubtext: "выезд 30–60 минут по Душанбе",
    trustTime: "За 1 час",
    trustTimeDesc: "мастер будет у вас",
    trustRating: "4.9",
    trustRatingDesc: "средний рейтинг мастеров",
    trustOrders: "5000+",
    trustOrdersDesc: "выполнено заказов в Душанбе",
    aboutTitle: "Мастер Час — сервис мастеров на дом в Душанбе",
    aboutDescription: "Мы помогаем жителям Душанбе быстро найти проверенного мастера для любых бытовых задач — от установки розетки до ремонта под ключ.",
    aboutFeature1Title: "Проверенные мастера",
    aboutFeature1Desc: "Каждый мастер проходит проверку документов и навыков. Работаем только с надёжными специалистами Душанбе.",
    aboutFeature2Title: "Цены в сомони",
    aboutFeature2Desc: "Прозрачные цены без скрытых доплат. Вы знаете стоимость до начала работ.",
    aboutFeature3Title: "Выезд по всему Душанбе",
    aboutFeature3Desc: "Работаем в районах Сино, Фирдавси, Шохмансур, Исмоили Сомони и пригороде.",
    aboutFeature4Title: "Поддержка 24/7",
    aboutFeature4Desc: "Аварийный мастер приедет даже ночью. Служба поддержки работает круглосуточно.",
    howItWorksTitle: "Как вызвать мастера — 3 простых шага",
    howItWorksStep1Title: "Выберите услугу",
    howItWorksStep1Desc: "Укажите, что нужно сделать: починить кран, установить розетку, собрать мебель.",
    howItWorksStep2Title: "Опишите задачу",
    howItWorksStep2Desc: "Добавьте адрес в Душанбе, телефон и удобное время — мастер подготовится заранее.",
    howItWorksStep3Title: "Мастер приедет",
    howItWorksStep3Desc: "Проверенный специалист приедет к вам домой и выполнит работу качественно.",
    howItWorksFooter: "Без лишних звонков. Заказ онлайн за 2 минуты.",
    categoriesTitle: "Услуги мастеров в Душанбе",
    categoriesDescription: "Выберите категорию и закажите мастера. Все цены в сомони.",
    categoryElectric: "Электрика",
    categoryPlumbing: "Сантехника",
    categoryCleaning: "Уборка",
    categoryFurniture: "Сборка мебели",
    categoryRenovation: "Отделка",
    categorySecurity: "Видеонаблюдение",
    categoryWelding: "Сварка",
    categoryRepair: "Ремонт техники",
    categorySmartHome: "Умный дом",
    categoryGarage: "Подвалы и гаражи",
    categoryTurnkey: "Ремонт под ключ",
    categoryOther: "Другие услуги",
    categoryEmergency: "Аварийный мастер 24/7",
    categoryEmergencyBadge: "Срочно",
    categoryPriceFrom: "аз",
    categoryOrderButton: "Вызвать мастера",
    categoryChooseServices: "Выбрать услуги",
    contactsTitle: "Свяжитесь с нами",
    contactsDescription: "Звоните, пишите в WhatsApp или Telegram — мы на связи 24/7.",
    contactsPhone: "Телефон",
    contactsEmail: "Почта",
    contactsWorkHours: "Режим работы",
    contactsWorkHoursValue: "24/7 — круглосуточно",
    becomeMasterTitle: "Станьте мастером в Душанбе",
    becomeMasterSubtitle: "Присоединяйтесь к команде Мастер Час — получайте заказы каждый день по всему Душанбе",
    becomeMasterBenefit1: "Заказы каждый день",
    becomeMasterBenefit2: "Свободный график",
    becomeMasterBenefit3: "Оплата сразу после работы",
    becomeMasterBenefit4: "Поддержка от команды 24/7",
    becomeMasterFormTitle: "Оставить заявку",
    becomeMasterFormName: "Ваше имя",
    becomeMasterFormPhone: "Телефон (+992...)",
    becomeMasterFormSpecialty: "Ваша специальность (электрик, сантехник...)",
    becomeMasterFormExperience: "Опыт работы (лет)",
    becomeMasterFormSubmit: "Отправить заявку",
    becomeMasterFormSuccess: "Раҳмат! Мы свяжемся с вами в ближайшее время.",
    servicesTitle: "Прайс-лист услуг",
    servicesSubtitle: "Все цены в сомони. Точная стоимость — после осмотра мастером.",
    serviceElectric: "Электрика",
    servicePlumbing: "Сантехника",
    serviceCleaning: "Уборка",
    serviceFurniture: "Сборка мебели",
    serviceRenovation: "Отделка",
    serviceSecurity: "Видеонаблюдение",
    serviceWelding: "Сварка",
    serviceBasement: "Подвалы и гаражи",
    serviceTurnkey: "Ремонт под ключ",
    serviceRepair: "Ремонт техники",
    serviceSmartHome: "Умный дом",
    serviceOther: "Другие услуги",
    formName: "Ваше имя",
    formPhone: "Телефон (+992...)",
    formService: "Выберите услугу",
    formDistrict: "Район Душанбе",
    formComment: "Опишите задачу (необязательно)",
    formSubmit: "Отправить заявку",
    formSuccess: "Раҳмат! Мы скоро свяжемся с вами",
    districtSino: "Сино",
    districtFirdausi: "Фирдавси",
    districtShomansur: "Шохмансур",
    districtIsmoili: "Исмоили Сомони",
    footerAboutText: "Мастер Час — сервис вызова мастеров на дом в Душанбе. Электрика, сантехника, уборка, ремонт — быстро и по честным ценам.",
    footerContacts: "Контакты",
    footerDistricts: "Районы Душанбе",
    footerRights: "© 2025 Мастер Час. Душанбе, Тоҷикистон. Ҳамаи ҳуқуқҳо ҳифз шудаанд.",
    footerServices: "Услуги",
    footerSubscriptions: "Тарифы",
    footerBecomeMaster: "Стать мастером",
    footerForBusiness: "Для бизнеса",
    footerPrivacy: "Конфиденциальность",
    footerTerms: "Условия",
    viewAllCategories: "Все категории услуг",
    learnMore: "Подробнее",
    qualityGuarantee: "Кафолати сифат",
    qualityGuaranteeDesc: "Если работа не устроит — мастер вернётся и исправит бесплатно",
    step: "Қадам",
    orderModalTitle: "Вызвать мастера",
    orderModalDesc: "Заполните форму — мы подберём мастера в вашем районе",
    orderModalSubmit: "Отправить",
    orderModalSuccess: "Дархост қабул шуд! Мы скоро свяжемся.",
  },
  tj: {
    navAbout: "Дар бораи мо",
    navCategories: "Хидматҳо",
    navMasters: "Устоҳо",
    navHowItWorks: "Тарзи кор",
    navContacts: "Тамос",
    navBecomeMaster: "Усто шавед",
    login: "Даромадан",
    logout: "Баромадан",
    cabinet: "Кабинет",
    admin: "Админ",
    masterCabinet: "Кабинети усто",
    clientCabinet: "Кабинети ман",
    subscription: "Обуна",
    heroTitle: "Усто ба хонаатон меояд",
    heroSubtitle: "Устоони боэътимод • Баромадан аз 30 дақиқа • Кафолати кор",
    heroDescription: "Мастер Час — хидмати даъвати усто ба хона дар Душанбе. Барқ, сантехника, тозакунӣ, таъмири техника ва дигар хидматҳо — зуд, боэътимод, бо нархҳои одилона дар сомонӣ.",
    heroOrderButton: "Усто даъват кунед",
    heroEmergencyButton: "🚨 Устои таъҷилӣ 24/7",
    heroEmergencySubtext: "баромадан 30–60 дақиқа дар Душанбе",
    trustTime: "Дар 1 соат",
    trustTimeDesc: "усто назди шумо меояд",
    trustRating: "4.9",
    trustRatingDesc: "рейтинги миёнаи устоон",
    trustOrders: "5000+",
    trustOrdersDesc: "фармоишҳо дар Душанбе иҷро шудаанд",
    aboutTitle: "Мастер Час — хидмати устоон дар Душанбе",
    aboutDescription: "Мо ба сокинони Душанбе кӯмак мекунем, ки зуд устои боэътимод пайдо кунанд — аз насби розетка то таъмири пурра.",
    aboutFeature1Title: "Устоони тасдиқшуда",
    aboutFeature1Desc: "Ҳар як усто тафтиши ҳуҷҷатҳо ва малакаро мегузарад. Танҳо бо мутахассисони боэътимоди Душанбе кор мекунем.",
    aboutFeature2Title: "Нархҳо дар сомонӣ",
    aboutFeature2Desc: "Нархҳои шаффоф бе пардохтҳои пинҳонӣ. Шумо нархро пеш аз оғози кор медонед.",
    aboutFeature3Title: "Баромадан дар тамоми Душанбе",
    aboutFeature3Desc: "Дар ноҳияҳои Сино, Фирдавсӣ, Шоҳмансур, Исмоилӣ Сомонӣ ва атрофи шаҳр кор мекунем.",
    aboutFeature4Title: "Дастгирии 24/7",
    aboutFeature4Desc: "Устои таъҷилӣ ҳатто шабона меояд. Хидмати дастгирӣ шабонарӯзӣ кор мекунад.",
    howItWorksTitle: "Чӣ тавр усторо даъват кардан — 3 қадами содда",
    howItWorksStep1Title: "Хидматро интихоб кунед",
    howItWorksStep1Desc: "Нишон диҳед, ки чӣ кор бояд кард: таъмири кран, насби розетка, ҷамъкунии мебел.",
    howItWorksStep2Title: "Вазифаро тавсиф кунед",
    howItWorksStep2Desc: "Суроға дар Душанбе, телефон ва вақти муносибро илова кунед.",
    howItWorksStep3Title: "Усто меояд",
    howItWorksStep3Desc: "Мутахассиси тасдиқшуда ба хонаатон меояд ва корро сифатнок иҷро мекунад.",
    howItWorksFooter: "Бе зангҳои зиёдатӣ. Фармоиш дар 2 дақиқа онлайн.",
    categoriesTitle: "Хидматҳои устоон дар Душанбе",
    categoriesDescription: "Категорияро интихоб кунед ва усторо даъват кунед. Ҳамаи нархҳо дар сомонӣ.",
    categoryElectric: "Барқ",
    categoryPlumbing: "Сантехника",
    categoryCleaning: "Тозакунӣ",
    categoryFurniture: "Ҷамъкунии мебел",
    categoryRenovation: "Ороиш",
    categorySecurity: "Видеоназорат",
    categoryWelding: "Ҷӯшкорӣ",
    categoryRepair: "Таъмири техника",
    categorySmartHome: "Хонаи зиракона",
    categoryGarage: "Зеризамин ва гаражҳо",
    categoryTurnkey: "Таъмири пурра",
    categoryOther: "Хидматҳои дигар",
    categoryEmergency: "Устои таъҷилӣ 24/7",
    categoryEmergencyBadge: "Зудӣ",
    categoryPriceFrom: "аз",
    categoryOrderButton: "Усто даъват кунед",
    categoryChooseServices: "Хидматро интихоб кунед",
    contactsTitle: "Бо мо тамос гиред",
    contactsDescription: "Занг занед, ба WhatsApp ё Telegram нависед — мо 24/7 дар тамос ҳастем.",
    contactsPhone: "Телефон",
    contactsEmail: "Почта",
    contactsWorkHours: "Тартиби корӣ",
    contactsWorkHoursValue: "24/7 — шабонарӯзӣ",
    becomeMasterTitle: "Дар Душанбе усто шавед",
    becomeMasterSubtitle: "Ба дастаи Мастер Час ҳамроҳ шавед — ҳар рӯз фармоиш гиред дар тамоми Душанбе",
    becomeMasterBenefit1: "Ҳар рӯз фармоишҳо",
    becomeMasterBenefit2: "Ҷадвали озод",
    becomeMasterBenefit3: "Пардохт фавран пас аз кор",
    becomeMasterBenefit4: "Дастгирии дастаи 24/7",
    becomeMasterFormTitle: "Дархост гузоред",
    becomeMasterFormName: "Номи шумо",
    becomeMasterFormPhone: "Телефон (+992...)",
    becomeMasterFormSpecialty: "Ихтисоси шумо (барқкор, сантехник...)",
    becomeMasterFormExperience: "Таҷрибаи кор (сол)",
    becomeMasterFormSubmit: "Фиристодани дархост",
    becomeMasterFormSuccess: "Раҳмат! Мо зуд бо шумо тамос мегирем.",
    servicesTitle: "Нархнома",
    servicesSubtitle: "Ҳамаи нархҳо дар сомонӣ. Нархи дақиқ — пас аз тафтиши усто.",
    serviceElectric: "Барқкорӣ",
    servicePlumbing: "Сантехника",
    serviceCleaning: "Тозакунӣ",
    serviceFurniture: "Ҷамъкунии мебел",
    serviceRenovation: "Ороиш",
    serviceSecurity: "Видеоназорат",
    serviceWelding: "Ҷӯшкорӣ",
    serviceBasement: "Зеризамин ва гаражҳо",
    serviceTurnkey: "Таъмири пурра",
    serviceRepair: "Таъмири техника",
    serviceSmartHome: "Хонаи зиракона",
    serviceOther: "Хидматҳои дигар",
    formName: "Номи шумо",
    formPhone: "Телефон (+992...)",
    formService: "Хидматро интихоб кунед",
    formDistrict: "Ноҳияи Душанбе",
    formComment: "Вазифаро тавсиф кунед (ихтиёрӣ)",
    formSubmit: "Фиристодани дархост",
    formSuccess: "Раҳмат! Мо зуд бо шумо тамос мегирем",
    districtSino: "Сино",
    districtFirdausi: "Фирдавсӣ",
    districtShomansur: "Шоҳмансур",
    districtIsmoili: "Исмоилӣ Сомонӣ",
    footerAboutText: "Мастер Час — хидмати даъвати усто ба хона дар Душанбе. Барқ, сантехника, тозакунӣ, таъмир — зуд ва бо нархҳои одилона.",
    footerContacts: "Тамос",
    footerDistricts: "Ноҳияҳои Душанбе",
    footerRights: "© 2025 Мастер Час. Душанбе, Тоҷикистон. Ҳамаи ҳуқуқҳо ҳифз шудаанд.",
    footerServices: "Хидматҳо",
    footerSubscriptions: "Тарифҳо",
    footerBecomeMaster: "Усто шавед",
    footerForBusiness: "Барои бизнес",
    footerPrivacy: "Сиёсати махфият",
    footerTerms: "Шартҳои истифода",
    viewAllCategories: "Ҳамаи категорияҳоро дидан",
    learnMore: "Бештар",
    qualityGuarantee: "Кафолати сифат",
    qualityGuaranteeDesc: "Агар кор маъқул нашавад — усто бармегардад ва ройгон ислоҳ мекунад",
    step: "Қадам",
    orderModalTitle: "Усто даъват кунед",
    orderModalDesc: "Формаро пур кунед — мо дар ноҳияи шумо усторо интихоб мекунем",
    orderModalSubmit: "Фиристодан",
    orderModalSuccess: "Дархост қабул шуд! Мо зуд тамос мегирем.",
  },
  en: {
    navAbout: "About Us",
    navCategories: "Services",
    navMasters: "Masters",
    navHowItWorks: "How It Works",
    navContacts: "Contacts",
    navBecomeMaster: "Become a Master",
    login: "Login",
    logout: "Logout",
    cabinet: "Dashboard",
    admin: "Admin",
    masterCabinet: "Master Dashboard",
    clientCabinet: "My Dashboard",
    subscription: "Subscription",
    heroTitle: "Your master will arrive today",
    heroSubtitle: "Verified masters • Arrival from 30 min • Work guarantee",
    heroDescription: "Master Chas is a home service marketplace in Dushanbe. Electrical, plumbing, cleaning, appliance repair and more — fast, reliable, at fair prices in somoni.",
    heroOrderButton: "Call a Master",
    heroEmergencyButton: "🚨 Emergency Master 24/7",
    heroEmergencySubtext: "arrival 30–60 min in Dushanbe",
    trustTime: "Within 1 hour",
    trustTimeDesc: "master arrives at your door",
    trustRating: "4.9",
    trustRatingDesc: "average master rating",
    trustOrders: "5000+",
    trustOrdersDesc: "orders completed in Dushanbe",
    aboutTitle: "Master Chas — Home Service in Dushanbe",
    aboutDescription: "We help Dushanbe residents quickly find a verified master for any household task — from socket installation to full renovation.",
    aboutFeature1Title: "Verified Masters",
    aboutFeature1Desc: "Every master undergoes document and skill verification. We work only with trusted Dushanbe specialists.",
    aboutFeature2Title: "Prices in Somoni",
    aboutFeature2Desc: "Transparent prices with no hidden fees. You know the cost before work begins.",
    aboutFeature3Title: "All of Dushanbe",
    aboutFeature3Desc: "We serve Sino, Firdavsi, Shohmansur, Ismoili Somoni districts and suburbs.",
    aboutFeature4Title: "24/7 Support",
    aboutFeature4Desc: "Emergency master available even at night. Support team works around the clock.",
    howItWorksTitle: "How to call a master — 3 simple steps",
    howItWorksStep1Title: "Choose a service",
    howItWorksStep1Desc: "Tell us what needs to be done: fix a faucet, install a socket, assemble furniture.",
    howItWorksStep2Title: "Describe the task",
    howItWorksStep2Desc: "Add your Dushanbe address, phone number, and preferred time.",
    howItWorksStep3Title: "Master arrives",
    howItWorksStep3Desc: "A verified specialist will come to your home and do the job right.",
    howItWorksFooter: "No extra calls. Order online in 2 minutes.",
    categoriesTitle: "Home Services in Dushanbe",
    categoriesDescription: "Choose a category and call a master. All prices in somoni.",
    categoryElectric: "Electrical",
    categoryPlumbing: "Plumbing",
    categoryCleaning: "Cleaning",
    categoryFurniture: "Furniture Assembly",
    categoryRenovation: "Finishing",
    categorySecurity: "CCTV",
    categoryWelding: "Welding",
    categoryRepair: "Appliance Repair",
    categorySmartHome: "Smart Home",
    categoryGarage: "Basements & Garages",
    categoryTurnkey: "Turnkey Renovation",
    categoryOther: "Other Services",
    categoryEmergency: "Emergency Master 24/7",
    categoryEmergencyBadge: "Urgent",
    categoryPriceFrom: "from",
    categoryOrderButton: "Call a Master",
    categoryChooseServices: "Choose Services",
    contactsTitle: "Contact Us",
    contactsDescription: "Call, write on WhatsApp or Telegram — we're available 24/7.",
    contactsPhone: "Phone",
    contactsEmail: "Email",
    contactsWorkHours: "Working hours",
    contactsWorkHoursValue: "24/7 — around the clock",
    becomeMasterTitle: "Become a Master in Dushanbe",
    becomeMasterSubtitle: "Join the Master Chas team — get orders every day across Dushanbe",
    becomeMasterBenefit1: "Daily orders",
    becomeMasterBenefit2: "Flexible schedule",
    becomeMasterBenefit3: "Payment right after the job",
    becomeMasterBenefit4: "Team support 24/7",
    becomeMasterFormTitle: "Submit Application",
    becomeMasterFormName: "Your name",
    becomeMasterFormPhone: "Phone (+992...)",
    becomeMasterFormSpecialty: "Your specialty (electrician, plumber...)",
    becomeMasterFormExperience: "Work experience (years)",
    becomeMasterFormSubmit: "Submit Application",
    becomeMasterFormSuccess: "Thank you! We will contact you soon.",
    servicesTitle: "Price List",
    servicesSubtitle: "All prices in somoni. Final cost confirmed after master inspection.",
    serviceElectric: "Electrical",
    servicePlumbing: "Plumbing",
    serviceCleaning: "Cleaning",
    serviceFurniture: "Furniture Assembly",
    serviceRenovation: "Finishing",
    serviceSecurity: "CCTV",
    serviceWelding: "Welding",
    serviceBasement: "Basements & Garages",
    serviceTurnkey: "Turnkey Renovation",
    serviceRepair: "Appliance Repair",
    serviceSmartHome: "Smart Home",
    serviceOther: "Other Services",
    formName: "Your Name",
    formPhone: "Phone (+992...)",
    formService: "Select Service",
    formDistrict: "Dushanbe District",
    formComment: "Describe the task (optional)",
    formSubmit: "Submit Request",
    formSuccess: "Thank you! We'll contact you soon",
    districtSino: "Sino",
    districtFirdausi: "Firdavsi",
    districtShomansur: "Shohmansur",
    districtIsmoili: "Ismoili Somoni",
    footerAboutText: "Master Chas — home service marketplace in Dushanbe. Electrical, plumbing, cleaning, repairs — fast and at fair prices.",
    footerContacts: "Contacts",
    footerDistricts: "Dushanbe Districts",
    footerRights: "© 2025 Master Chas. Dushanbe, Tajikistan. All rights reserved.",
    footerServices: "Services",
    footerSubscriptions: "Plans",
    footerBecomeMaster: "Become a Master",
    footerForBusiness: "For Business",
    footerPrivacy: "Privacy Policy",
    footerTerms: "Terms of Service",
    viewAllCategories: "View all service categories",
    learnMore: "Learn more",
    qualityGuarantee: "Quality Guarantee",
    qualityGuaranteeDesc: "If the work doesn't satisfy — the master will return and fix it for free",
    step: "Step",
    orderModalTitle: "Call a Master",
    orderModalDesc: "Fill out the form — we'll find a master in your area",
    orderModalSubmit: "Submit",
    orderModalSuccess: "Request accepted! We'll contact you soon.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("ru");

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)["ru"]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
